### ISSUE TITLE
We should have a Dockerfile and we should move it "user.username == 'armzi'" into .env file.

### ISSUE THREAD

**Issue by Aitthi** [thananon/twitch_tools#13]
We should have a Dockerfile and we should move it.` "user.username == 'armzi'` into the `.env` file for easy testing and use in other channels.

**Comment by thananon** [comment]
![image](https://user-images.githubusercontent.com/7318806/107865502-cbb22c00-6e2c-11eb-8e88-14ada8c16c74.png)
