### ISSUE TITLE
Attack system

### ISSUE THREAD

**Issue by kaozaza2** [thananon/twitch_tools#35]
I think bot need attack system with below rule

* Player attack to bot, bot attack back
* When player attack miss, bot attack back 100% accurate
* When bot die, give exp and coin to player who last kill bot and all online player 1 coin
* When player die, timeout player for 5 minutes and coin drop 30%

**Comment by kaozaza2** [comment]
Can control this function by !raid [on|off]

**Comment by thananon** [comment]
Great idea. Bot as a raid boss can be fun. Let me think about this.

**Comment by kaozaza2** [comment]
Ok, if you okay for this i'll open PR
