### ISSUE TITLE
A front page to display GIF.

### ISSUE THREAD

**Issue by thananon** [thananon/twitch_tools#5]
We want to display GIF on screen when some event happen in our bot. Similar to what twitchalert has. Especially when someone wins big in `!gacha`.

**Comment by rayriffy** [comment]
what if creating an http server for greenscreen window, and play media (even `<video />`) one and use obs to chroma key those out?

**Comment by Ba5nanas** [comment]
http can't streaming if you need streaming use protocol rtmp sending to server streaming.

**Comment by rayriffy** [comment]
Streaming is already one by his preferred software. http is only to provide another layer to streaming software (OBS etc.) that can be chroma key, and play any content via web components.

**Comment by thananon** [comment]
> what if creating an http server for greenscreen window, and play media (even `<video />`) one and use obs to chroma key those out?

This is what I meant. I just need a webpage that reacts to events generated by `9armbot`.

**Comment by rayriffy** [comment]
I've created PR at #10, test and make a review please. I cannot set @thananon to be reviewer

**Comment by thananon** [comment]
Thanks @rayriffy. I looked at the PR. It looks ok to me. I will give it a try tonight.
